CREATE TABLE rol(
	rolId BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nombreRol VARCHAR(50) NOT NULL,
    descripcion VARCHAR(200) NOT NULL
);

CREATE TABLE usuario(
	usuarioId BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(50) NOT NULL,
    `password` VARCHAR(100) NOT NULL,
	rolId BIGINT NOT NULL,
    FOREIGN KEY (rolId) REFERENCES rol(rolID)
); 